apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-app-deployment
  labels:
    app: reverse-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverse-app
  template:
    metadata:
      labels:
        app: reverse-app
    spec:
      containers:
        - name: reverse-app
          image: signavio-app2
          imagePullPolicy: Never
          ports:
            - containerPort: 5000